"""Contrats de données : ce qui circule entre les modules.

Aucune entrée/sortie, aucun algorithme. Voir ``docs/DICTIONNAIRE_DONNEES.md``,
généré depuis les docstrings de ce paquet.
"""

from mountain_perf.schemas.activity import Activity, TrackPointStream
from mountain_perf.schemas.clock import (
    CENTRAL_CONVENTION_INDEX,
    CLOCK_CONVENTIONS,
    CLOCK_KIND_DESCRIPTIONS,
    CLOCKS,
    INTERVAL_STATE_DESCRIPTIONS,
    Clock,
    ClockConvention,
    ClockKind,
    ClockPartition,
    ClockTotals,
    IntervalState,
    StopEpisode,
)
from mountain_perf.schemas.common import (
    ELEVATION_RANGE_M,
    GRADE_RANGE,
    HEART_RATE_RANGE_BPM,
    LATITUDE_RANGE_DEG,
    LONGITUDE_RANGE_DEG,
    QUALITY_FLAG_DESCRIPTIONS,
    SPORT_DESCRIPTIONS,
    UTC_OFFSET_RANGE_S,
    QualityFlag,
    SourceRef,
    Sport,
)
from mountain_perf.schemas.curve import CurveProvenance, PaceCurve
from mountain_perf.schemas.matching import (
    POINT_STATUS_DESCRIPTIONS,
    REGIME_CLASS_DESCRIPTIONS,
    REGIME_DESCRIPTIONS,
    SEGMENT_EXCLUSION_DESCRIPTIONS,
    AdmittedTotals,
    Coverage,
    MatchResult,
    PointStatus,
    Regime,
    RegimeClass,
    ScorePointObservation,
    ScoreSegmentObservation,
    SegmentExclusion,
    SensitivityConfiguration,
)
from mountain_perf.schemas.outing import (
    ARTIFACT_ROLE_DESCRIPTIONS,
    DATA_SET_DESCRIPTIONS,
    OUTING_LABEL_DESCRIPTIONS,
    REFERENCE_KIND_DESCRIPTIONS,
    UNAVAILABILITY_DESCRIPTIONS,
    ArtifactRef,
    ArtifactRole,
    DataSet,
    Outing,
    OutingLabel,
    Performance,
    ReferenceKind,
    RetentionDecision,
    RouteReference,
    Unavailability,
)
from mountain_perf.schemas.parameters import ParameterSet, ParameterSpec
from mountain_perf.schemas.projection import Passage, Projection, Segment
from mountain_perf.schemas.reference import (
    TIMING_CONVENTION_DESCRIPTIONS,
    ObservedPassage,
    ReferencePerformance,
    TimingConvention,
)
from mountain_perf.schemas.route import (
    POINT_KIND_DESCRIPTIONS,
    NamedPoint,
    PointKind,
    ResolvedPoint,
    Route,
    RouteProfile,
)
from mountain_perf.schemas.trace import RecordedTrace
from mountain_perf.validation import ContractError

__all__ = [
    "ARTIFACT_ROLE_DESCRIPTIONS",
    "CENTRAL_CONVENTION_INDEX",
    "CLOCKS",
    "CLOCK_CONVENTIONS",
    "CLOCK_KIND_DESCRIPTIONS",
    "DATA_SET_DESCRIPTIONS",
    "ELEVATION_RANGE_M",
    "GRADE_RANGE",
    "HEART_RATE_RANGE_BPM",
    "INTERVAL_STATE_DESCRIPTIONS",
    "LATITUDE_RANGE_DEG",
    "LONGITUDE_RANGE_DEG",
    "OUTING_LABEL_DESCRIPTIONS",
    "POINT_KIND_DESCRIPTIONS",
    "POINT_STATUS_DESCRIPTIONS",
    "QUALITY_FLAG_DESCRIPTIONS",
    "REFERENCE_KIND_DESCRIPTIONS",
    "REGIME_CLASS_DESCRIPTIONS",
    "REGIME_DESCRIPTIONS",
    "SEGMENT_EXCLUSION_DESCRIPTIONS",
    "SPORT_DESCRIPTIONS",
    "TIMING_CONVENTION_DESCRIPTIONS",
    "UNAVAILABILITY_DESCRIPTIONS",
    "UTC_OFFSET_RANGE_S",
    "Activity",
    "AdmittedTotals",
    "ArtifactRef",
    "ArtifactRole",
    "Clock",
    "ClockConvention",
    "ClockKind",
    "ClockPartition",
    "ClockTotals",
    "ContractError",
    "Coverage",
    "CurveProvenance",
    "DataSet",
    "IntervalState",
    "MatchResult",
    "NamedPoint",
    "ObservedPassage",
    "Outing",
    "OutingLabel",
    "PaceCurve",
    "ParameterSet",
    "ParameterSpec",
    "Passage",
    "Performance",
    "PointKind",
    "PointStatus",
    "Projection",
    "QualityFlag",
    "RecordedTrace",
    "ReferenceKind",
    "ReferencePerformance",
    "Regime",
    "RegimeClass",
    "ResolvedPoint",
    "RetentionDecision",
    "Route",
    "RouteProfile",
    "RouteReference",
    "ScorePointObservation",
    "ScoreSegmentObservation",
    "Segment",
    "SegmentExclusion",
    "SensitivityConfiguration",
    "SourceRef",
    "Sport",
    "StopEpisode",
    "TimingConvention",
    "TrackPointStream",
    "Unavailability",
]
